# Generated by Django 4.2.8 on 2024-05-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_profile",
            field=models.ImageField(
                blank=True, default="static/duck.jpg", upload_to=""
            ),
        ),
    ]
