# Generated by Django 4.2.8 on 2024-05-23 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_nickname',
            new_name='user_profile',
        ),
    ]
