# Generated by Django 4.2.8 on 2024-05-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
