# Generated by Django 4.2.8 on 2024-05-20 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='adult',
            new_name='upcoming',
        ),
    ]
