# Generated by Django 4.2.8 on 2024-05-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_alter_actor_profile_logo_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boxoffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.TextField()),
                ("rank", models.IntegerField()),
                ("name", models.TextField()),
                ("code", models.IntegerField()),
                ("acc_aud", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="actor",
            name="actor_popularity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="director",
            name="director_popularity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="Provider",
            field=models.ManyToManyField(null=True, to="movie.provider"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="adult",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="popularity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster_path",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="video",
            field=models.ManyToManyField(null=True, to="movie.video"),
        ),
    ]
