# Generated by Django 4.2.8 on 2024-05-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movie_genre_id_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_logo_path',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
