# Generated by Django 4.2.8 on 2024-05-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0003_boxoffice_alter_actor_actor_popularity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="Provider",
            field=models.ManyToManyField(to="movie.provider"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="video",
            field=models.ManyToManyField(to="movie.video"),
        ),
    ]
