# Generated by Django 4.2.8 on 2024-05-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_provider_provider_id_provider_provider_logo_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Provider',
            field=models.ManyToManyField(to='movie.provider'),
        ),
    ]
