# Generated by Django 4.2.8 on 2024-05-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0004_alter_movie_provider_alter_movie_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxoffice",
            name="movie",
            field=models.ManyToManyField(to="movie.movie"),
        ),
    ]
