# Generated by Django 4.2.8 on 2024-05-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.ManyToManyField(to='movie.video'),
        ),
        migrations.AddField(
            model_name='video',
            name='official',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_key',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_name',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_site',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
