# Generated by Django 4.2.8 on 2024-05-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0005_boxoffice_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxoffice",
            name="en_name",
            field=models.TextField(null=True),
        ),
    ]
