# Generated by Django 4.2.8 on 2024-05-16 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0007_producer_actor_actor_id_actor_actor_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Keyword",
        ),
    ]
