# Generated by Django 4.2.8 on 2024-05-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0008_delete_keyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster_path",
            field=models.TextField(default="Unknown"),
            preserve_default=False,
        ),
    ]
