# Generated by Django 4.2.8 on 2024-05-13 14:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Entry',
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
    ]
